version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI_API=342857567033.dkr.ecr.us-east-2.amazonaws.com/ldma-api
      - REPOSITORY_URI_DATABASE=342857567033.dkr.ecr.us-east-2.amazonaws.com/ldma-database
      - REPOSITORY_URI_PROCESSOR=342857567033.dkr.ecr.us-east-2.amazonaws.com/ldma-processor
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $REPOSITORY_URI_API:latest .
      - docker tag $REPOSITORY_URI_API:latest $REPOSITORY_URI_API:$IMAGE_TAG
      - docker build -f trip-event-database/docker/postgres/Dockerfile -t $REPOSITORY_URI_DATABASE:latest .
      - docker tag $REPOSITORY_URI_DATABASE:latest $REPOSITORY_URI_DATABASE:$IMAGE_TAG
      - docker build -f trip-event-database/docker/analytics_processor/Dockerfile -t $REPOSITORY_URI_PROCESSOR:latest ./trip-event-database
      - docker tag $REPOSITORY_URI_PROCESSOR:latest $REPOSITORY_URI_PROCESSOR:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI_API:latest
      - docker push $REPOSITORY_URI_API:$IMAGE_TAG
      - docker push $REPOSITORY_URI_DATABASE:latest
      - docker push $REPOSITORY_URI_DATABASE:$IMAGE_TAG
      - docker push $REPOSITORY_URI_PROCESSOR:latest
      - docker push $REPOSITORY_URI_PROCESSOR:$IMAGE_TAG
artifacts:
    files:
      - '**/*'