version: '3'
services:
  phoenix:
    # image: 342857567033.dkr.ecr.us-east-2.amazonaws.com/ldma-api:latest
    build:
      context: .
    environment:
      # Variables to connect to our Postgres server
      PGUSER: postgres
      PGPASSWORD: Hc3spD5MxuNcXu2v9#-PwpMZTm
      PGDATABASE: tripdb
      PGPORT: 5432
      # Hostname of our Postgres container
      PGHOST: tripeventdb
    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container
      - "80:4000"
    depends_on:
      - tripeventdb
    volumes:
      - .:/usr/src/app
    networks:
       - backend
      
  tripeventdb:
    image: timescale/timescaledb-postgis:1.2.1-pg11
    environment:
      POSTGRES_PASSWORD: Hc3spD5MxuNcXu2v9#-PwpMZTm
      POSTGRES_USER: postgres
      POSTGRES_DB: tripdb
    command: postgres -c config_file=/etc/postgresql.conf
    volumes:
      - ./trip-event-database/PostgresConfig/postgres_init:/docker-entrypoint-initdb.d
      - ./trip-event-database/PostgresConfig/postgresql.conf:/etc/postgresql.conf
      - ./trip-event-database/backup:/var/lib/postgresql/backup
      - db_datadir:/var/lib/postgresql/data
    networks:
       - backend
    ports: 
      - 17171:5432
   
volumes:
  db_datadir:

networks:
     backend:
      driver: bridge