version: '3'
services:
  phoenix:
    # image: 342857567033.dkr.ecr.us-east-2.amazonaws.com/ldma-api:latest
    build:
      context: .
    environment:
      # Variables to connect to our Postgres server
      PGUSER: postgres
      PGPASSWORD: Hc3spD5MxuNcXu2v9#-PwpMZTm
      PGDATABASE: tripdb
      PGPORT: 5432
      # Hostname of our Postgres container
      PGHOST: tripeventdb
    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container
      - "80:4000"
    depends_on:
      - tripeventdb
    volumes:
      - .:/usr/src/app
    networks:
       - backend
  
  processor:
    #image: 342857567033.dkr.ecr.us-east-2.amazonaws.com/ldma-processor:latest
    build:
      context: ./trip-event-database
      dockerfile: docker/analytics_processor/Dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: Hc3spD5MxuNcXu2v9#-PwpMZTm
    depends_on:
      # The db container needs to be started before we start this container
      - tripeventdb
    networks:
      - backend

  tripeventdb:
     # image: 342857567033.dkr.ecr.us-east-2.amazonaws.com/ldma-database:latest
    build:
      context: ./trip-event-database/docker/postgres
    environment:
      POSTGRES_PASSWORD: Hc3spD5MxuNcXu2v9#-PwpMZTm
      POSTGRES_USER: postgres
      POSTGRES_DB: tripdb
    command: postgres -c config_file=/etc/postgresql.conf
    volumes:
      - ./trip-event-database/docker/postgres/postgres_init:/docker-entrypoint-initdb.d
      - ./trip-event-database/docker/postgres/postgresql.conf:/etc/postgresql.conf
      - db_datadir:/var/lib/postgresql/data
    networks:
       - backend
    ports: 
      - 17171:5432
   
volumes:
  db_datadir:

networks:
     backend:
      driver: bridge