@echo off

echo Starting mysql service...
plink -ssh -T -l debian -pw temppwd -m setup_connection 192.168.7.2 > NUL
echo Enabling SSH Tunnel...
start plink -T -l debian -pw temppwd 192.168.7.2 -L 3306:localhost:3306
timeout /t 2 > NUL
echo Exporting data...
java -jar -Xmx10G .\SQLWorkbench\sqlworkbench.jar -profile="BBLogger" -libdir=".\SQLWorkbench" -command="WbExport -type='text' -timestampFormat='y-M-d H:m:s.SSSSSS' -blobType='pghex' -header='true' -append='false' -delimiter=';' -quoteChar='\"' -file='ExportedData\rawData.csv' -sourceTable='rawData';"
echo Shutting down...
taskkill /im plink.exe > NUL
::plink -ssh -T -l debian -pw temppwd -m terminate_connection 192.168.7.2 > NUL